spring.application.name=enqueteApp

#データベース接続URL
spring.datasource.url=jdbc:mysql://localhost:3306/enquete_db

#使用するデータベースのドライバークラス
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#データベース接続時のユーザー名およびパスワード
spring.datasource.username=root
spring.datasource.password=root

#MyBatis
mybatis.mapper-locations=classpath*:templates/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=katachi.spring.sample.entity

#SQLスクリプトの初期化モードを設定（開発終了時にコメントアウトする）
spring.sql.init.mode=always

#Log Level
logging.level.com.example=debug

spring.cache.type = simple